In [54]:
# scipy knn 
import numpy as np
import torch
import matplotlib.pyplot as plt
import time
dataset = [[10.,  9.],[ 9., 18.],[16., 13.],[11., 15.],[12., 14.],[18., 12.],[ 2., 14.], [ 6., 18.],[ 9.,  9.],[10.,  8.],[ 6., 17.],[ 5.,  3.],[13., 19.],[ 3., 18.],[ 8., 17.],[ 9.,  7.],[13., 18.],[15.,  4.],[13., 16.]]
dataset = np.array(dataset)
point = np.array([3,0])

In [55]:
import scipy.spatial as spt
begin = time.time()
for i in range(1000):
    mytree = spt.cKDTree(dataset, leafsize=10)
    distances, indices = mytree.query(point,k=5)
print((time.time()-begin)/1000)

0.00018806815147399904


In [56]:
print(distances, indices)

[ 3.60555128  9.21954446 10.63014581 10.81665383 11.40175425] [11 15  9  8  0]


In [57]:
from knn_cuda import KNN
dataset = torch.from_numpy(dataset).cuda()
point = torch.from_numpy(point).view(1,-1).cuda()
#  time.time()
begin = time.time()
for i in range(1000):
    knn_tree = KNN(k=5, transpose_mode=True)
    # print(type(dataset),type(point))
    distances, indices = knn_tree(dataset, point)
print((time.time()-begin)/1000)
print(distances, indices)

0.0003317713737487793
tensor([[ 3.6056,  9.2195, 10.6301, 10.8167, 11.4018]], device='cuda:0') tensor([[11, 15,  9,  8,  0]], device='cuda:0')


In [52]:
from sklearn.neighbors import KDTree
begin = time.time()
for i in  range(1000):
    tree = KDTree(dataset, leaf_size=100)
    point = point.reshape(1,-1)
print((time.time()-begin)/1000)
d, i = tree.query(point, k=5)
print(d,i)

0.00011891913414001465
[[ 3.60555128  9.21954446 10.63014581 10.81665383 11.40175425]] [[11 15  9  8  0]]
